apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::499427809291:role/eks-cluster-CodePipelineGitHub-1UDOL6NW6IESK
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::499427809291:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-02T17:36:23Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3767"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 96957bc5-92ec-480d-96a1-24580e1fdc99
