# apiVersion: v1
# data:
#   mapRoles: "- groups:\n  - system:masters\n  rolearn: arn:aws:iam::499427809291:role/UdacityFlaskDeployCBKubectRole\n
#     \ username: build\n- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn:
#     arn:aws:iam::499427809291:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-17C402QC9VF6L\n
#     \ username: system:node:{{EC2PrivateDNSName}}  \n"
#   mapUsers: |
#     []
# kind: ConfigMap
# metadata:
#   creationTimestamp: "2021-09-02T17:36:23Z"
#   name: aws-auth
#   namespace: kube-system
#   resourceVersion: "3767"
#   uid: 96957bc5-92ec-480d-96a1-24580e1fdc99

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::499427809291:role/<EXISTENT_ROLE_INFORMATION>
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::499427809291:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-02T17:36:23Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3767"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 96957bc5-92ec-480d-96a1-24580e1fdc99
